language: python

python:
- '3.6'
- '3.7'
- '3.8'

before_install:
- pip3 install -U --only-binary=numpy --only-binary=scipy numpy scipy

install:
- pip3 install pytest pytest-cov coveralls
- python setup.py install

script:
- pytest --cov=polyrat --cov-branch  tests/

after_success:
- coveralls


jobs:
  include:
    - stage: deploy
      python: 3.8
      install: python setup.py install
      script: pytest tests/
      deploy:
        distributions: sdist
        on:
          branch: master
          tags: true
        provider: pypi
        username: __token__
        password: 
          secure: uYh6vAfroEyoo7UUqAkk3Db2t0MeFHTh9yzKjZpJJUo0EDlDH0wZKSH/RGI4H+HEpntDQpGUhlQtBULUJnkceRjJOYr0sEIJo8RCbZqYl4XdMA1P+bVufHB6NlwWBfkpvGOeV0TI600pLk72Rd+fFeVMothyBxJyP3pXSMqB6ZzUBDqBiZwF8D3bibuygEBVjtp/ONB9kE08uQzLq1OT5UsOkObaegAbwo1Ora5MUnkVh50tyZ/UIcB4XCDoOogQPee5IIdG/CNg44MO7MGylGqr66ImvPUjt4UzvMtu6zXsjTB8ji4rOABhLhhHEi5TsDWSKI6AgN6GQPtVOjT+A8BAMU/zd9XZCgjN1uYw6L+Y+kJE+qmaHR8i5bEI5ThoPfBdP8qdLNw+Y9bS9N+lR5QLGGrNM0Ndr/USIwvfubjcjyTneBgyFHGjfom5pN7UCc6+tNbo3VFnp5i6q0sCQofFQYNh+gVFbDxYd4c/s3VwBN3irC2LTQnbLSzpSUlJgu8MIF1HxTrCsSErp7SUpW6LhpLbrkbLPe8HvNNYs8/0KHECidthhmlmAjEn4GLs4C/fmpjuR+ZjFtvl27b13pbSwNJiKnkHIUSqr8VHcJzuLOxZTJTfJ5HQfAJaoJSzZZrG/DclaHNnewwJm0Rw6TcrDaddaM7LYxbntamQT5A=
